apiVersion: apps/v1
kind: Deployment
metadata:
  name: pruebaimagen
  labels:
    app: pruebaimagen
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: pruebaimagen
        service: webapi
    spec:
      containers:
        - name: webapi
          image: exploredocker.azurecr.io/pruebaimagen:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: pruebaimagen
  labels:
    app: pruebaimagen
    service: webapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapi
